//InField
(function(c){c.InFieldLabels=function(e,f,d){var a=this;a.$label=c(e);a.label=e;a.$field=c(f);a.field=f;a.$label.data("InFieldLabels",a);a.showing=!0;a.init=function(){var b;a.options=c.extend({},c.InFieldLabels.defaultOptions,d);setTimeout(function(){""!==a.$field.val()?(a.$label.hide(),a.showing=!1):(a.$label.show(),a.showing=!0)},200);a.$field.focus(function(){a.fadeOnFocus()}).blur(function(){a.checkForEmpty(!0)}).bind("keydown.infieldlabel",function(b){a.hideOnChange(b)}).bind("paste",function(){a.setOpacity(0)}).change(function(){a.checkForEmpty()}).bind("onPropertyChange",
function(){a.checkForEmpty()}).bind("keyup.infieldlabel",function(){a.checkForEmpty()});0<a.options.pollDuration&&(b=setInterval(function(){""!==a.$field.val()&&(a.$label.hide(),a.showing=!1,clearInterval(b))},a.options.pollDuration))};a.fadeOnFocus=function(){a.showing&&a.setOpacity(a.options.fadeOpacity)};a.setOpacity=function(b){a.$label.stop().animate({opacity:b},a.options.fadeDuration);a.showing=0<b};a.checkForEmpty=function(b){""===a.$field.val()?(a.prepForShow(),a.setOpacity(b?1:a.options.fadeOpacity)):
a.setOpacity(0)};a.prepForShow=function(){a.showing||(a.$label.css({opacity:0}).show(),a.$field.bind("keydown.infieldlabel",function(b){a.hideOnChange(b)}))};a.hideOnChange=function(b){16!==b.keyCode&&9!==b.keyCode&&(a.showing&&(a.$label.hide(),a.showing=!1),a.$field.unbind("keydown.infieldlabel"))};a.init()};c.InFieldLabels.defaultOptions={fadeOpacity:0.5,fadeDuration:300,pollDuration:0,enabledInputTypes:"text search tel url email password number textarea".split(" ")};c.fn.inFieldLabels=function(e){var f=
e&&e.enabledInputTypes||c.InFieldLabels.defaultOptions.enabledInputTypes;return this.each(function(){var d=c(this).attr("for"),a;d&&(d=document.getElementById(d))&&(a=c.inArray(d.type,f),-1===a&&"TEXTAREA"!==d.nodeName||new c.InFieldLabels(this,d,e))})}})(jQuery);

// jQuery listnav plugin. Copyright (c) 2009 iHwy, Inc. Author: Jack Killpatrick. Version 2.1 (08/09/2009). Visit http://www.ihwy.com/labs/jquery-listnav-plugin.aspx for more information.
(function(a){a.fn.listnav=function(n){var c=a.extend({},a.fn.listnav.defaults,n),e="_abcdefghijklmnopqrstuvwxyz-".split(""),m=!1;c.prefixes=a.map(c.prefixes,function(a){return a.toLowerCase()});return this.each(function(){function n(){var b,h,d,e,g=0<c.prefixes.length;a(f).children().each(function(){e=a(this);h="";b=a.trim(e.text()).toLowerCase();""!=b&&(g&&(d=b.split(" "),1<d.length&&-1<a.inArray(d[0],c.prefixes)&&(h=d[1].charAt(0),r(h,e,!0))),h=b.charAt(0),r(h,e))})}function r(b,a,c){/\W/.test(b)&&
(b="-");isNaN(b)||(b="_");a.addClass("ln-"+b);void 0==g[b]&&(g[b]=0);g[b]++;c||s++}function t(b){if(a(b).hasClass("all"))return s;b=g[a(b).attr("class").split(" ")[0]];return void 0!=b?b:0}function u(){c.showCounts&&k.mouseover(function(){l.css({top:a(".a",d).slice(0,1).offset({margin:!1,border:!0}).top-l.outerHeight({margin:!0})})});c.showCounts&&(a("a",d).mouseover(function(){var b=a(this).position().left,c=a(this).outerWidth({margin:!0})-1+"px",d=t(this);l.css({left:b,width:c}).text(d).show()}),
a("a",d).mouseout(function(){l.hide()}));a("a",d).click(function(){a("a.ln-selected",d).removeClass("ln-selected");var b=a(this).attr("class").split(" ")[0];"all"==b?(f.children().show(),f.children(".ln-no-match").hide(),p=!0):(p?(f.children().hide(),p=!1):""!=q&&f.children(".ln-"+q).hide(),0<t(this)?(f.children(".ln-no-match").hide(),f.children(".ln-"+b).show()):f.children(".ln-no-match").show(),q=b);a.cookie&&null!=c.cookieName&&a.cookie(c.cookieName,b);a(this).addClass("ln-selected");a(this).blur();
if(m||null==c.onClick)m=!1;else c.onClick(b);return!1})}function v(){for(var b=[],a=1;a<e.length;a++)0==b.length&&b.push('<a class="all" href="#">ALL</a><a class="_" href="#">0-9</a>'),b.push('<a class="'+e[a]+'" href="#">'+("-"==e[a]?"Other":e[a].toUpperCase())+"</a>");return'<div class="ln-letters">'+b.join("")+"</div>"+(c.showCounts?'<div class="ln-letter-count" style="display:none; position:absolute; top:0; left:0; width:20px;">0</div>':"")}var k,f,d,l;k=a("#"+this.id+"-nav");f=a(this);var g=
{},s=0,p=!0,q="";(function(){k.append(v());d=a(".ln-letters",k).slice(0,1);c.showCounts&&(l=a(".ln-letter-count",k).slice(0,1));n();f.append('<li class="ln-no-match" style="display:none">'+c.noMatchText+"</li>");if(c.flagDisabled)for(var b=0;b<e.length;b++)void 0==g[e[b]]&&a("."+e[b],d).addClass("ln-disabled");u();c.includeAll||f.show();c.includeAll||a(".all",d).remove();c.includeNums||a("._",d).remove();c.includeOther||a(".-",d).remove();a(":last",d).addClass("ln-last");a.cookie&&null!=c.cookieName&&
(b=a.cookie(c.cookieName),null!=b&&(c.initLetter=b));if(""!=c.initLetter)m=!0,a("."+c.initLetter.toLowerCase(),d).slice(0,1).click();else if(c.includeAll)a(".all",d).addClass("ln-selected");else for(b=c.includeNums?0:1;b<e.length;b++)if(0<g[e[b]]){m=!0;a("."+e[b],d).slice(0,1).click();break}})()})};a.fn.listnav.defaults={initLetter:"",includeAll:!0,incudeOther:!1,includeNums:!0,flagDisabled:!0,noMatchText:"No matching entries",showCounts:!0,cookieName:null,onClick:null,prefixes:[]}})(jQuery);

